### ISSUE TITLE
Need to make the last row better

### ISSUE THREAD

**Issue by Matysh** [tin-cat/jquery-mosaic#13]
Thanks for the nice plugin! I use it on my portfilio site!
maxRowHeightPolicy 'tail' - good improvement!
But! Sometimes last row still looks ugly.
I suggest the following:
1) Disallow the case when there is only one element on the last line. In this case, we can move another element from the previous line (of course, if there are more than 2 elements). Or apply 'skip' option.
2) Possibility to center the last line if maxRowHeightPolicy = 'tail'

**Comment by Matysh** [comment]
One more possibility - add option like 'maxLastRowHeight'

**Comment by tin-cat** [comment]
Hi Matysh! Thanks for your suggestions. As per your first point, the 'skip' option does precisely that. I don't think moving an element from the previous row to fill in the last one would be in tune with the purpose of the plugin, as this will cause violations of the specified maxRowHeight on that row, and make it become very unpredictable.

Centering the items on the last row when maxRowHeightPolicy allows for incomplete last rows is a great suggestion, I will consider adding it into a future release. By now, you can do that by simply tweaking jquery.mosaic.css, or overlading your own css classes making the items become inline-block, and then centering them with text-align: center.

As per your last suggestion, could you please how the "maxLastRowHeight" option you suggest would work? 

Meow!

**Comment by Matysh** [comment]
For example: 
maxRowHeight = 250
maxLastRowHeight = 500
if height of the last row < 500 with 'oversize' => use 'oversize'
else apply 'skip'

**Comment by tin-cat** [comment]
Hi Matysh, thanks for the suggestion about maxLastRowHeight! It might be a great feature to be implemented in the future, as an intermediate solution between the 'tail' and the 'skip' policy. Since this plugin is aimed to build rectangular, beautiful mosaics without empty gaps, the maxLastRowHeight option might help attain that in certain situations.

I would surely be interested in a pull request from someone implementing this change! ;)
