### ISSUE TITLE
Lightbox with Mosaic

### ISSUE THREAD

**Issue by FullDome** [tin-cat/jquery-mosaic#20]
When I try to add the popular lightbox plugin, then jquery mosaic won't work.
This works, even with lazyload added:
    `<img class="lazyload" data-src="image.jpg" width="450" height="300" />`

But this won't work:
    `<a href="bigimage.jpg" rel="lightbox[roadtrip]" title="mytitle"><img class="lazyload" data-src="image.jpg" width="450" height="300"></a>`

I tried to add the image as background of a div, but that also won't work.
Is there any way to make it work, since I really like jquery mosaic more than masonry.js

**Comment by tin-cat** [comment]
Hi @FullDome! I might need to do some tests, but unless the lightbox plugin is messing too much with the dom, it should work.

jQuery Mosaic needs to know either the width and the height, or the aspect ratio of each element, and I think the problem you're having might be related to that.

Indeed, jQuery Mosaic works fine also with `<A>` and `<DIV>` elements instead of `<IMG>`, but you should be giving him a hint on their aspect ratio to let him do his thing. I think your example is not working because you're not giving the <A> element any implicit size, try this:

`<a href="bigimage.jpg" rel="lightbox[roadtrip]" title="mytitle" width="300" height="200"><img class="lazyload" data-src="image.jpg" width="450" height="300"></a>`

or this:

`<a href="bigimage.jpg" rel="lightbox[roadtrip]" title="mytitle" data-aspect-ratio="1.5"><img class="lazyload" data-src="image.jpg" width="450" height="300"></a>`

Of course you would need to know these sizes (or the aspect ratio) in advance, that would be the downside. But if you're building your mosaic with PHP or similar, it shouldn't be a problem.

Cheers!

**Comment by FullDome** [comment]
Thank you for your help!
The image size or ratio is being handled by the lightbox. The smaller image is the one being handled with jquerymosaic. 
Even if I add the size or resolution for the big image, jquerymosaic won't work.

I noticed that when I add a link, it doesn't work. So it probably doesn't concern the lightbox, but a href:

`<a href="bigimage.jpg"><img class="lazyload" data-src="smallimage.jpg" width="450" height="300" /></a>`

**Comment by tin-cat** [comment]
Hi, I think you're having conflicts by using two plugins that both might be trying to set the size of an element. It is true that jQuery Mosaic will read the width and height of each element if it has been set (either manually, or, say, by another plugin like Lightbox), but you'll need to be sure that jQuery Mosaic is called _after_ Lightbox has done its thing.

I suggest the possible following scenarios for you to follow:

- Find out whether Lightbox has some kind of a callback function that is called after the lightbox has been set up and try calling jQuery Mosaic in that function to ensure Lightbox has set the sizes before calling jQuery Mosaic.
- Having two plugins messing with image sizes at the same time seems too overkill to me. I would try to use the Lightbox only for the purpose of showing a zoomed version of the image in a popup, not to set image sizes in my DOM.

Let me know if that works for you!

**Comment by FullDome** [comment]
It's definitly not the lightbox. When I remove it and just add "a href" to any link, the images get a huge margin.

When I add a link on any image on the example page, then the plugin adds huge margins to the images and loses responsiveness: https://jquery-mosaic.tin.cat/example_basic.php

**Comment by tin-cat** [comment]
It definitely seems that that huge margin (or padding) to the elements of the mosaic is being applied from your CSS, check your css!

**Comment by FullDome** [comment]
The padding is added on my page, but also yours. I thought it came from the lightbox plugin, but it appears when I add a link to the images. Also on your example page. See image attached, where I added a link and copied the image twice:

![jquerymosaic_href](https://user-images.githubusercontent.com/41142413/42723385-f7add638-875c-11e8-869c-de956fad1546.jpg)

**Comment by tin-cat** [comment]
It's not a padding, it looks more like the plugin hasn't been executed, or it took the wrong sizes. I'm afraid I would need to take a look at your code, just having some description of the behavior and screenshoots won't do the trick.

Send me your code so I can reproduce the problem here and I might be taking a quick look at it whenever I can. The tin cat is very busy. Please check all my suggestions first.

Meow.

**Comment by FullDome** [comment]
Dear tincat,
I used your suggestions. But adding a link to an image in my code or your code makes the same thing.
The screenshot is your code from your website. I just added a link to an image in the mosaic div.

If you add an url or image link to a photo inside the jquerymosaic, the plugin won't excecute.

**Comment by tin-cat** [comment]
The problem is that there are many thins that could cause this. For example, It seems to me the plugin is working well and the `<A>` has been resized to the adequate size, but you're expecting it to also resize the image you placed inside the `<A>`, this is not what the plugin does. Take into account that the plugin resizes the container element, it doesn't touches anything inside.

There's another example in the source (https://jquery-mosaic.tin.cat/example_advanced.php) to exemplify what you're trying to do. You'll see in this example that each image in the mosaic is linkable (which is what you're trying to achieve), but in order for the image to be resized, it's being applied as a background image of the container element (the one that gets resized by the plugin), with a background-size that allows for it to grow to the container's size. Since jQuery Mosaic resized the container and not the contents, this is one possible solution to achieve it.

Take a deep dive into this example and let me know if that solves your doubt.

Cheers!

**Comment by FullDome** [comment]
Applying an image as background image made it possible to use a link!

`<a class="item withImage" href="bigimage.jpg" rel="lightbox[roadtrip]" width="640" height="425" style="background-image: url('smallimage.jpg');"></a>`

Thank you very much! Issue solved!

**Comment by tin-cat** [comment]
Glad you solved it! Cheers!
