### ISSUE TITLE
Support for VIDEO element

### ISSUE THREAD

**Issue by borekl** [tin-cat/jquery-mosaic#21]
Hello, can we please get support for `VIDEO` elements in the gallery? I want to have mixed images+videos and jquery.mosaic seems to ignore the videos. This can be perhaps worked around by wrapping the videos with   ##`DIV`s, but that's just unnecessary annoyance. The change needed is trivial, just add VIDEO to getItems and into CSS and it works fine.

**Comment by tin-cat** [comment]
Hi @borekl, sounds like a great addition, will take that into account, I hope some avid developer out there also hears you and wants to contribute it!

In any case, since jQuery Mosaic can work with any kind of contents, not just IMGs, I see no problem on putting videos inside the DIV elements, with some simple CSS trickery, as you say, that should work nice. Take a look at the example title "[Creating a mosaic of DIVs instead of images](http://jquery-mosaic.tin.cat/example_divs.php)".

Meow!
