### ISSUE TITLE
Add minRowHeight or minElementWidth

### ISSUE THREAD

**Issue by DenislavParvanov** [tin-cat/jquery-mosaic#22]
It will be very nice to add one of this options

**Comment by tin-cat** [comment]
Hi @DenislavParvanov, sounds great! Could you comment how do you imagine those options would work in the following scenarios?

- When specifying a minRowHeight, what happens if, with the given elements, the minRowHeight cannot be reached, thus a regular mosaic cannot be created?
- When specifying a minRowHeight, how jQuery Mosaic should react if minElementWidth has also been specified and the aspect ratio for a certain element cannot be attained as a result?

I think of jQuery Mosaic primarily as a responsive way of creating mosaics. I think the responsive nature of the generated mosaics is a primary goal of the project, so giving too many specific sizes and limits starts to defeat the responsive logic of the plugin pretty fast. Do you think implementing those two options, if the conflicts between those kind of limiting parameters could be solved, and the complexity of managing exceptions was acceptable, would go against this essence?

Thanks!

**Comment by tin-cat** [comment]
Since I'm not getting any answer and it's been a long time, I'm closing this issue.
