### ISSUE TITLE
aspect-ratio is broken when size of images are big.

### ISSUE THREAD

**Issue by leftglass** [tin-cat/jquery-mosaic#30]
I found this issue when I uploaded this web application to the online server.
This application works fine when it is launched inside local PC, but it is broken when it is on the web server.

I found a culprit. That is an image file of 4.8MB jpg. The file is at the second position that is supposed to lie in the middle of the first row on my PC screen. I suspect the file is a culprit because it is loaded at last even though it is on the  second position.
I have no idea why the aspect ratio is broken only on the web server. The second file is loaded at last on my local computer too. It is instantly loaded, but at last. On the web, it is loaded at last and it takes a few seconds, and ends up with broken aspect ratio of other images.
My gallery is fixed if I delete the image file of 4.8MB, but application itself is not fixed, you know.

I'd appreciate if developers fix  this issue or add some safeguard against accidental break of  aspect ratio for user images uploaded on the web application .

**Comment by tin-cat** [comment]
Hi @leftglass , are you relying on jQuery Mosaic automatically guessing the image aspect ratio, or are you specifically setting it via the width/height or data-aspect-ratio properties on the IMG tags?

Take into account that if you are not letting jQuery Mosaic know each image size or aspect ratio via the properties mentioned above, he will have to guess them by itself. Since the image you're using is quite big, it will take a while to load in the browser (specially when it's loaded remotely from a server and not in a local development environment). JQuery Mosaic tries to guess the image size, but since it's not loaded yet , he can't.

jQuery Mosaic does not wait for images to be loaded (it's up to you to implement this if you need that specific behavior), thats why jQuery Mosaic works better and is really happy when you specify either the width and height of your images on the HTML code, or the data-aspect-ratio property. Through these, jQuery Mosaic has the information he needs to properly build the mosaic even if the images have not been loaded yet.

Hope this helps.

Cheers!

**Comment by leftglass** [comment]
I am not specifically setting it.
It sounds like your advice would solve my problem.
Thanks.
