### ISSUE TITLE
Automatically detect dimensions 

### ISSUE THREAD

**Issue by manfuku** [tin-cat/jquery-mosaic#5]
Currently the script works only if all the images have defined widths and heights. For example:

works <img src="path.jpg" width="32" height=32">
doesn't work <img src="path.jpg">

Is there a way where I don't have to put the dimensions? The images have different aspect ratios.

**Comment by tin-cat** [comment]
Thanks! You're right, jquery-mosaic requires the width and height to be specified on each element of the mosaic in order to calculate its aspect ratio. You can specify a "data-aspect-ratio" attribute instead, like this:

&lt;img src="file.jpg" data-aspect-ratio="1.4"&gt;

But I'm afraid at this moment jquery-mosaic is not able to calculate the aspect ratio of an element that has no implicit size.

Because of this limitation, it's more than likely that you want to use jquery-mosaic along with some server-side processing like PHP in order to retrieve the image sizes. Most examples on the repository itself use this technique.

There's maybe a way to add this feature: retrieving the browser-calculated element sizes might work but I guess it would require the script to wait until the images are loaded, and might create a weird effect on the screen.

I will give it a thought, contributions welcomed!

**Comment by bryan-farris** [comment]
For what it's worth, I'm trying to do something similar to this using a function to calculate the the image sizes with [imagesloaded](http://imagesloaded.desandro.com/) and then running Mosaic.

Here is what the grid looks like before Mosaic is called: https://cl.ly/2n061E403s03

And here is what it looks like after Mosaic is called: https://cl.ly/0B1i1X0o3n2Q

Why are the heights being adjusted so much from element to element? Shouldn't the first "x" images share the same height, moving to the next row, repeating that pattern as in your examples?

Thanks!

**Comment by tin-cat** [comment]
Hi Bryan, the algorithm iterates row by row by fitting images to the same height until they reach the specified maxRowHeight parameter. So, yes, all images in each row should have the same height. If you're not seeing that in your implementation, the only thing I can think of is that Mosaic is not being able to guess the sizes of the images via the info on the DOM, just be sure to call Mosaic only after width and height as been set on each mosaic element. I can see in your first screenshot that you're already doing that, but are you sure you're calling Mosaic after that?

Take a look at the base.getItemHeight, base.getItemWidth and base.getItemAspectRatio to understand how this plugin guesses the items sizes!

Cheers!

**Comment by bryan-farris** [comment]
Thanks for the quick reply! I'm still not sure what's going on here. I am definitely calling Mosaic well after the images have gotten their sizes applied inline. I made a quick video of the page: https://cl.ly/2p263S0R1J0J

In this video I'm calling Mosaic on `(window).load` and even after that, it's inside of a `setTimeout` function to make sure it's got an exaggerated delay. I also noticed that it's changing the width to match the height, in this case 280 x 280. Any thoughts are appreciated!

**Comment by tin-cat** [comment]
Hi @bryan-farris ! It's difficult to diagnose the problem with the video capture alone, but I would look into that "edd_download" css class that's assigned to each item to see if it's assigning some kind of size property that may interfere. I would then look into the "edd_downloads_list" and "edd_download_columns_0" css classes that are assigned to the wrapper container with the id  "stocky_downloads_list", it really seems those are the ones interfering. It seems you're using some kind of css framework and you're trying to use both the "column" capabilities of that CSS framework along with the Mosaic plugin. It that's the problem, your shouldn't be using both at the same time, try to isolate the mosaic to avoid your css framework acting on the mosaic div and its items, it might work! ;)
