### ISSUE TITLE
AJAX Image loading

### ISSUE THREAD

**Issue by jleifeld** [tin-cat/jquery-mosaic#6]
Hey,
this plugin is amazing! Is it possible to add photos with AJAX to reduce load times? My Scenario is a photographer site with many photos (50+).

Thanks, Jannis

**Comment by tin-cat** [comment]
Hi JLeifeld, thanks! Glad you liked it. At this point I'm not considering implementing this kind of functionality because I think it's better to keep it as a simpler plugin aimed to more low level implementations, so more higher level implementations with complex features like the one you suggested can be implemented by other developers by creating parallel projects, not by adding this functionalities to this plugin.

For example, is should be relatively simple to keep adding more items programmatically via javascript to the mosaic (for example, as a result of an ajax query, as you suggested), and then call the "fit" method on the plugin to make it appear correctly placed on the mosaic.

You can add new items to the mosaic DIV programmatically by doing something like:

`$('#mosaic').append('<img src="image.jpg" width="300" height="200" />');`

And then, ask the plugin to refit all the items again by doing:

`$('#mosaic').Mosaic('fit');`

That should work.

Thanks!
